# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecognitionImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecognitionImage
  pod 'ImageViewer.swift', '~> 3.0'
  
  target 'RecognitionImageTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
